---
# Configure the DC to prepare the domain
- hosts: all
  strategy: free
  tasks:
    - include_role:
        name: domain
      when: "'dc' in group_names"

# Run common tasks on all Windows machines in parallel
- hosts: windows
  roles:
    - common
    - juju4.win_eventlog
    - juju4.win_audit

# Domain-join clients and run post-domain configuration in parallel
- hosts: all
  strategy: free
  tasks:
    - include_role:
        name: dc
      when: "'dc' in group_names"
    - include_role: 
        name: win10xdr
      when: "'win10xdr' in group_names"
    - include_role: 
        name: win10def
      when: "'win10def' in group_names"
    - include_role: 
        name: linux
      when: "'linux' in group_names"
          
- hosts: syslog
  roles:
    - bodsch.syslog-ng

